### PR TITLE
New Compass Widget

### PR DESCRIPTION
**Pull request by timmathews**
Add compass rose styled pointer, full display of compass, numeric and
textual representations of heading angle.

screen shot 2015-08-23 at 12 34 36 am

### CODE REVIEW

**Comment by tkurki** [comment]
Cool. Shouldn't the rose rotate as well?

**Comment by timmathews** [comment]
How about this?

screen shot 2015-08-23 at 9 36 37 pm

**Comment by tkurki** [comment]
With node launched by `bin/n2k-from-file` the compass branch gives me js errors in console:

image

**Comment by tkurki** [comment]
Now that I look at it the degree field could maybe loose the decimals? Anyway, :+1:

**Pull request merged**
