### PR TITLE
Option to set a local instrumentlabel

### PR DESCRIPTION
**Pull request by SamHoulder**
Option to set a local instrumentlabel, universal, analog/digital
Adds props.localLabel if label changes.
Defaults to props.label if props.localLabel not set or empty.

### CODE REVIEW

**Comment by cmotelet** [comment]
This option may seem easy for the user, who can make changes directly in the GUI.
But it was already available before, via the `.signalk/baseDeltas.json` file on the server.
Personally, I prefer options distributed by the server and available to all users, but I've noticed that this isn't necessarily the opinion of the community.
So why not have 2 options, local and remote.

The help file should be updated to explain how to use this option (same for `Decimals` option).
https://github.com/SignalK/instrumentpanel/blob/master/lib/help/help.md?plain=1#L345
How to activate it, how to reset it, the difference between local and remote overload on the server.

It's true that I didn't explicitly refer to the `displayName` key in the online help:
https://github.com/SignalK/instrumentpanel/blob/master/lib/help/help.md?plain=1#L380
but rather in the general FAQ: 
https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data-eg-displayname

**Comment by cmotelet** [comment]
When there is an overload with the `displayName` in `baseDeltas.json`, the user doesn't know if it's a local overload or coming from the server.
image

**Comment by cmotelet** [comment]
The `Label` is not available in `Analog` mode.

image

**Comment by tkurki** [comment]
Sigh, metadata editing is in pretty sad state, could use a bit of developer love.

**Comment by bkcorwin** [comment]
I'll agree that the proper solution is probably a better way to edit metadata.  However, in the meantime for many users I think a local label implementation like this would be stellar.

**Comment by tkurki** [comment]
Metadata editing will probably be published soon https://github.com/SignalK/signalk-server/pull/1730

**Comment by cmotelet** [comment]
Cancelled, metdata `Label` can now be edited directly on the server in the “Data Browser” menu ( Key: displayName).
image

**Pull request closed without merging**
