### PR TITLE
Settings for widgets (with multiple compass widgets as example) & responsive settings layout

### PR DESCRIPTION
**Pull request by tkurki**
Implement the capability to provide a settings panel for an individual widget, like the compass or the windmeter.

The case in point is being able to choose between a compass rose display and a reading display.

image
image

In addition this pull request restyles the settings panel as a responsive grid layout.

### CODE REVIEW

**Comment by tkurki** [comment]
Continuing work in this branch, don't merge.

**Comment by sumps** [comment]
Have tested the latest version of Instrument Panel and here are the results;
- [ ] IP multiplies by 60 rather than divides by 60 when 1/min units are selected for revolutions
- [ ]  IP displays pressures in Pa which due to their value causes the data in the panels to be too large and over write things, suggest default is KPa and it also needs to provide PSI and Bar unit options
- [ ]  IP defaults to showing Engine Hours (Run Time) in seconds and it should convert to Hours and not worry about any other unit options
- [ ]  IP needs to default to degs/min for Rate of Turn rather than  radians/s
- [ ]  In the Settings page, the displays are too large and you can only see a small part of each value

**Comment by tkurki** [comment]
This branch is getting out of hand - unless somebody objects I'll merge rsn.

**Comment by timmathews** [comment]
firefox_screenshot_2016-05-22t22-20-59 630z
This needs work in FF before it can be merged

**Comment by tkurki** [comment]
Thanks! Better now?

Anything else?

**Comment by timmathews** [comment]
Looks good to me, except I think having the disconnect button on the right is a little awkward when everything else (including connect) is pulled left. I don't think that should hold up the merge though.

**Comment by tkurki** [comment]
I moved it away from configuration buttons after clicking it accidentally a few times on my phone.

Disconnect is something you do very rarely, that's why I changed it to an icon, to take up less real estate, especially on a phone.

**Pull request merged**
