### PR TITLE
Multiple values/sources

### PR DESCRIPTION
**Pull request by tkurki**
This PR makes InstrumentPanel aware of multiple sources/values for a data item.

Normal gauges that only show one data item are created on the fly for each source. 

Windmeter, which shows multiple data items in a single gauge, is created when the first data item eligible to be a Windmeter data source is discovered. After that it starts to listen to all data sources.

StreamBundle now publishes new data items in a stream. InstrumentPanel handles the new items reactively: it first offers the item to all the existing gauges. If none accept then a new gauge is created.

There is still functionality to do, like in windmeter you should be able to say which sources you want to use / prefer, but I'd like to pull these to master so that any other development work will not result in merge hell.

### CODE REVIEW

**Comment by tkurki** [comment]
@timmathews would you have time to review this?

**Comment by timmathews** [comment]
> On Apr 13, 2016, at 2:22 AM, Teppo Kurki <notifications@github.com> wrote:
> 
> @timmathews <https://github.com/timmathews> would you have time to review this?
> 

Sure, I’ll take a look today.

**Comment by timmathews** [comment]
It would be wonderful if you could add some comments to the code. I'm trying to follow along, but the bacon/streambundle stuff is mystifying to me.

**Comment by timmathews** [comment]
I've started adding comments on the v2.0 branch, see connectionindicator, gridjson, util/baconmodelmixin and hopefully some more by the time you see this.

**Comment by timmathews** [comment]
Merged manually. Thought GH would see that. Guess not :disappointed: 

Delete branch and start again from HEAD?

**Pull request closed without merging**
