### PR TITLE
fixing Safari browsers and react jsx issues

### PR DESCRIPTION
**Pull request by vyacht**
1. Adding cookies to allow issues with local storage in Safari's private browsing mode
2. Adding presets for react to process jsx

### CODE REVIEW

**Comment by tkurki** [comment]
Are you sure the cookie-based storage works? The json for my pretty trivial InstrumentPanel setup was 4076 characters, and http://browsercookielimits.squawky.net reports 4097 as the max cookie value length for my OS X Safari.

As all data stored in the cookie will be gone after the private browsing session ends I don't think it makes sense to make the effort to store the data at all in this case. Returning an empty data set on retrieval and ignoring errors when saving would make sense in this case.

**Comment by tkurki** [comment]
A fresh clone of this PR and npm install && npm run build fails with 
```
ERROR in ./lib/ui/main.js
Module build failed: ReferenceError: [BABEL] /private/tmp/instrumentpanel/lib/ui/main.js: Unknown option: direct.presets
    at Logger.error (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/private/tmp/instrumentpanel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/private/tmp/instrumentpanel/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/private/tmp/instrumentpanel/node_modules/babel-loader/index.js:71:12)
/tmp/instrumentpanel (master) $ npm -v
3.7.3
/tmp/instrumentpanel (master) $ node -v
v5.9.0
```

**Comment by vyacht** [comment]
re: local storage - I agree that cookies are not ideal. Writing to localStorage is a generally not allowed on Safari iOS 5 and 6 and I read about issues in some iOS 7 and 8 versions. Its not limited to private browsing. 

I guess its the question if you want to support iPad 1 in a limited way or not at all.

re: npm 3.7.3 - I am on 1.3.10 (as in Ubuntu 14.04) - and getting instrumentpanel to work there is painful and doesn't work without those changes. I guess its a problem many will have. Maybe I get around to upgrade eventually.

**Comment by tkurki** [comment]
Npm 1.3.10 is really ancient, I don't think it makes sense to support development on that old versions. Why not upgrade?

As the two commits are unrelated from general perspective and supporting storing the grid layout/settings is not feasible with the cookie approach I'm closing this.

**Comment by tkurki** [comment]
Npm 1.3.10 is really ancient, I don't think it makes sense to support development on that old versions. Why not upgrade?

As the two commits are unrelated from general perspective and supporting storing the grid layout/settings is not feasible with the cookie approach I'm closing this.

**Comment by tkurki** [comment]
See #25

**Pull request closed without merging**
